import { useMemo, useState } from 'react';
import { ChevronRight, Save, Sparkles, Sword, Shield, RotateCcw, Footprints, Hammer, Gem, Package } from 'lucide-react';

type Faction='Wei'|'Shu'|'Wu'|'Warlords';
type General={id:string;name:string;title:string;faction:Faction;role:string;hp:number;atk:number;range:number;move:number;skill:string;skillPower:number;ultimate:string;ultimatePower:number;equipment:string};
type Status='none'|'stun'|'burn'|'slow'|'guard';
type Terrain='plain'|'forest'|'hill'|'water'|'fort';
type EquipmentState={level:number;rarity:number;equipped:boolean;optionA:number;optionB:number};
type SaveData={floor:number;gold:number;gems:number;level:number;equipLevel:number;owned:string[];materials:number;equipment:Record<string,EquipmentState>};
type Unit=General&{team:'player'|'enemy';x:number;y:number;currentHp:number;maxHp:number;acted:boolean;rage:number;buff:number;movePoints:number;status:Status;statusTurns:number};
const W=7,H=6,saveKey='infinite-three-kingdoms-save-v2';
const terrain:Terrain[]=Array.from({length:W*H},(_,i)=>i===17||i===18||i===24?'forest':i===11||i===12?'hill':i===26||i===27?'water':i===32?'fort':'plain');
const terrainName:Record<Terrain,string>={plain:'평지',forest:'숲',hill:'고지',water:'수로',fort:'진지'};
const terrainCost:Record<Terrain,number>={plain:1,forest:2,hill:1,water:99,fort:1};
const generals:General[]=[
{id:'liu-bei',name:'유비',title:'인덕의 군주',faction:'Shu',role:'지원',hp:120,atk:22,range:2,move:3,skill:'인덕의 격려',skillPower:0,ultimate:'인덕의 대의',ultimatePower:0,equipment:'쌍검'},
{id:'guan-yu',name:'관우',title:'미염공',faction:'Shu',role:'전사',hp:150,atk:38,range:1,move:3,skill:'청룡참',skillPower:28,ultimate:'청룡언월도',ultimatePower:55,equipment:'청룡언월도'},
{id:'zhang-fei',name:'장비',title:'만인지적',faction:'Shu',role:'수호',hp:190,atk:28,range:1,move:2,skill:'호통',skillPower:0,ultimate:'장판교 포효',ultimatePower:34,equipment:'장팔사모'},
{id:'zhao-yun',name:'조운',title:'상산의 용',faction:'Shu',role:'기병',hp:135,atk:34,range:1,move:4,skill:'용진',skillPower:18,ultimate:'칠진칠출',ultimatePower:48,equipment:'용담창'},
{id:'zhuge-liang',name:'제갈량',title:'와룡',faction:'Shu',role:'책사',hp:95,atk:30,range:3,move:2,skill:'천뢰',skillPower:24,ultimate:'공성계',ultimatePower:42,equipment:'백우선'},
{id:'cao-cao',name:'조조',title:'위무제',faction:'Wei',role:'책사',hp:125,atk:29,range:2,move:3,skill:'간웅의 명령',skillPower:0,ultimate:'위무의 천명',ultimatePower:36,equipment:'의천검'},
{id:'xiahou-dun',name:'하후돈',title:'독안의 맹장',faction:'Wei',role:'전사',hp:160,atk:35,range:1,move:3,skill:'맹격',skillPower:20,ultimate:'독안참',ultimatePower:45,equipment:'칠성도'},
{id:'sun-quan',name:'손권',title:'강동의 호랑이',faction:'Wu',role:'지원',hp:130,atk:27,range:2,move:3,skill:'강동의 결의',skillPower:0,ultimate:'강동패왕',ultimatePower:30,equipment:'벽옥검'},
{id:'lu-bu',name:'여포',title:'천하무쌍',faction:'Warlords',role:'기병',hp:180,atk:48,range:1,move:4,skill:'천하무쌍',skillPower:42,ultimate:'신마난무',ultimatePower:70,equipment:'방천화극'},
{id:'diao-chan',name:'초선',title:'경국지색',faction:'Warlords',role:'지원',hp:90,atk:24,range:2,move:3,skill:'매혹',skillPower:0,ultimate:'폐월의 춤',ultimatePower:32,equipment:'금선연'}];
const defaultEquip=():Record<string,EquipmentState>=>Object.fromEntries(generals.map(g=>[g.id,{level:0,rarity:1,equipped:true,optionA:0,optionB:0}]));
const defaultSave:SaveData={floor:1,gold:5000,gems:300,level:1,equipLevel:0,owned:generals.slice(0,5).map(g=>g.id),materials:120,equipment:defaultEquip()};
const loadSave=():SaveData=>{try{const raw=JSON.parse(localStorage.getItem(saveKey)||'{}');const base=defaultEquip();for(const g of generals){const old=raw.equipment?.[g.id];if(old)base[g.id]={level:old.level||0,rarity:old.rarity||1,equipped:old.equipped!==false,optionA:old.optionA||0,optionB:old.optionB||0};else if(raw.equipLevel)base[g.id]={level:raw.equipLevel,rarity:1,equipped:true,optionA:0,optionB:0};}return{...defaultSave,...raw,equipment:base,materials:raw.materials??120}}catch{return defaultSave}};
const dist=(a:{x:number;y:number},b:{x:number;y:number})=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const equipFor=(g:General,s:SaveData)=>s.equipment[g.id]||{level:0,rarity:1,equipped:true,optionA:0,optionB:0};
const rarityName=(r:number)=>['','일반','고급','희귀','영웅','전설'][r]||'전설';
const rarityFor=(lv:number)=>lv>=15?5:lv>=10?4:lv>=5?3:lv>=3?2:1;
const optionNames=['공격력 +','최대HP +','치명타 +','스킬 위력 +'];
const optionValue=(kind:number,lv:number)=>kind===0?lv*2:kind===1?lv*5:kind===2?Math.floor(lv/2):kind===3?lv:0;

export default function App(){
 const[saveData,setSaveData]=useState<SaveData>(()=>loadSave());
 const[screen,setScreen]=useState<'home'|'tower'|'generals'|'summon'|'battle'|'inventory'>('home');
 const[selected,setSelected]=useState('guan-yu');const[target,setTarget]=useState<string|null>(null);const[units,setUnits]=useState<Unit[]>([]);const[turn,setTurn]=useState<'player'|'enemy'>('player');const[log,setLog]=useState<string[]>(['천탑 전투 준비 완료.']);
 const selectedUnit=units.find(u=>u.id===selected);const selectedGeneral=generals.find(g=>g.id===selected)||generals[0];
 const addLog=(s:string)=>setLog(v=>[s,...v].slice(0,8));const persist=(n:SaveData)=>{setSaveData(n);localStorage.setItem(saveKey,JSON.stringify(n));};
 const team=useMemo(()=>generals.filter(g=>saveData.owned.includes(g.id)).slice(0,5),[saveData.owned]);
 const enhance=()=>{const e=equipFor(selectedGeneral,saveData);if(e.level>=20)return addLog('전용장비가 최대 강화입니다.');const cost=(e.level+1)*5;if(saveData.materials<cost)return addLog(`강화 재료가 부족합니다. 필요 ${cost}`);const lv=e.level+1;const next={...e,level:lv,rarity:rarityFor(lv),optionA:e.optionA||((selectedGeneral.id.length+lv)%4),optionB:e.optionB||((selectedGeneral.name.length+lv+1)%4)};persist({...saveData,equipLevel:0,materials:saveData.materials-cost,equipment:{...saveData.equipment,[selectedGeneral.id]:next}});addLog(`${selectedGeneral.name} ${selectedGeneral.equipment} +${lv} 강화! 옵션 ${optionNames[next.optionA]}${optionValue(next.optionA,lv)}, ${optionNames[next.optionB]}${optionValue(next.optionB,lv)}`)};
 const reroll=()=>{const e=equipFor(selectedGeneral,saveData);if(e.level<3)return addLog('옵션 재설정은 장비 +3부터 가능합니다.');if(saveData.materials<20)return addLog('옵션석이 부족합니다.');let a=Math.floor(Math.random()*4),b=Math.floor(Math.random()*4);if(b===a)b=(b+1)%4;persist({...saveData,materials:saveData.materials-20,equipment:{...saveData.equipment,[selectedGeneral.id]:{...e,optionA:a,optionB:b}}});addLog(`${selectedGeneral.name} 옵션 재설정 완료.`)};
 const toggleEquip=()=>{const e=equipFor(selectedGeneral,saveData);persist({...saveData,equipment:{...saveData.equipment,[selectedGeneral.id]:{...e,equipped:!e.equipped}}});};
 const levelUp=()=>{const c=saveData.level*300;if(saveData.gold<c)return addLog(`금화가 부족합니다. 필요 ${c}`);persist({...saveData,level:saveData.level+1});};
 const summon=()=>{if(saveData.gems<30)return addLog('보옥이 부족합니다.');const locked=generals.filter(g=>!saveData.owned.includes(g.id));if(!locked.length)return addLog('모든 장수를 보유했습니다.');const g=locked[Math.floor(Math.random()*locked.length)];persist({...saveData,gems:saveData.gems-30,owned:[...saveData.owned,g.id]});addLog(`${g.name} 영입! ${g.equipment} 획득`);};
 const stat=(g:General)=>{const e=equipFor(g,saveData);const lv=e.equipped?e.level:0;let hp=g.hp+(saveData.level-1)*12+lv*10,atk=g.atk+(saveData.level-1)*3+lv*4;for(const k of [e.optionA,e.optionB]){const v=optionValue(k,lv);if(k===0)atk+=v;if(k===1)hp+=v;}return{hp,atk};};
 const startBattle=()=>{const ps=team.map((g,i)=>{const st=stat(g);return{...g,...st,maxHp:st.hp,team:'player' as const,x:i%3,y:5-Math.floor(i/3),currentHp:st.hp,acted:false,rage:0,buff:0,movePoints:g.move,status:'none' as Status,statusTurns:0}});const ids=saveData.floor%10===0?['lu-bu','xiahou-dun','cao-cao']:['xiahou-dun','zhang-fei','sun-quan'];const es=ids.map((id,i)=>{const g=generals.find(x=>x.id===id)!;const st=stat(g);return{...g,...st,maxHp:st.hp+saveData.floor*5,team:'enemy' as const,x:4+i%2,y:i+1,currentHp:st.hp+saveData.floor*5,acted:false,rage:0,buff:0,movePoints:g.move,status:'none' as Status,statusTurns:0}});setUnits([...ps,...es]);setSelected(team[1]?.id||team[0]?.id||'liu-bei');setTarget(null);setTurn('player');setLog([`천탑 ${saveData.floor}층 ${saveData.floor%10===0?'보스전! ':''}전투 시작.`]);setScreen('battle');};
 const damage=(a:Unit,b:Unit,bonus=0)=>Math.max(1,a.atk+a.buff+bonus+(terrain[b.y*W+b.x]==='fort'?8:terrain[b.y*W+b.x]==='hill'?4:0)-Math.floor(b.maxHp*.08)-(b.status==='guard'?8:0));
 const moveUnit=(x:number,y:number)=>{if(!selectedUnit||selectedUnit.team!=='player'||selectedUnit.acted||turn!=='player')return;const occupied=units.some(u=>u.currentHp>0&&u.x===x&&u.y===y);if(occupied)return addLog('다른 장수가 있는 칸은 이동할 수 없습니다.');const cell=terrain[y*W+x],cost=terrainCost[cell];if(cost>=99)return addLog('수로에는 이동할 수 없습니다.');const d=dist(selectedUnit,{x,y});if(d===0||d>selectedUnit.movePoints)return addLog(`이동력 부족: ${selectedUnit.movePoints} MP`);setUnits(us=>us.map(u=>u.id===selectedUnit.id?{...u,x,y,movePoints:u.movePoints-cost}:u));addLog(`${selectedUnit.name} → ${terrainName[cell]} (${cost} MP)`);};
 const basicAttack=()=>{if(!selectedUnit||selectedUnit.acted||turn!=='player')return;const t=units.find(u=>u.id===target&&u.team==='enemy'&&u.currentHp>0);if(!t||dist(selectedUnit,t)>selectedUnit.range)return addLog('공격 범위 안의 적을 선택하세요.');const d=damage(selectedUnit,t);setUnits(us=>us.map(u=>u.id===selectedUnit.id?{...u,acted:true,rage:Math.min(100,u.rage+25)}:u.id===t.id?{...u,currentHp:Math.max(0,u.currentHp-d),rage:Math.min(100,u.rage+15)}:u));addLog(`${selectedUnit.name}의 기본 공격! ${d} 피해`);setTarget(null);};
 const skill=()=>{if(!selectedUnit||selectedUnit.acted||turn!=='player')return;const t=units.find(u=>u.id===target&&u.team==='enemy'&&u.currentHp>0);if(selectedUnit.skill==='인덕의 격려'){const ally=units.find(u=>u.team==='player'&&u.id!==selectedUnit.id&&u.currentHp>0);if(!ally)return;setUnits(us=>us.map(u=>u.id===ally.id?{...u,buff:u.buff+8,status:'guard',statusTurns:1}:u.id===selectedUnit.id?{...u,acted:true,rage:Math.min(100,u.rage+20)}:u));addLog(`${ally.name} 공격력 +8 / 보호`);return}if(selectedUnit.skill==='강동의 결의'){setUnits(us=>us.map(u=>u.team==='player'&&u.currentHp>0?{...u,buff:u.buff+3,status:'guard',statusTurns:1}:u.id===selectedUnit.id?{...u,acted:true,rage:Math.min(100,u.rage+20)}:u));addLog('아군 전체 공격력 +3 / 보호');return}if(selectedUnit.skill==='간웅의 명령'){setUnits(us=>us.map(u=>u.team==='enemy'&&u.currentHp>0?{...u,atk:Math.max(1,u.atk-6),status:'slow',statusTurns:1}:u.id===selectedUnit.id?{...u,acted:true,rage:Math.min(100,u.rage+20)}:u));addLog('적 전체 공격력 -6 / 감속');return}if(!t||dist(selectedUnit,t)>selectedUnit.range+1)return addLog('스킬 대상이 없습니다.');const stun=['호통','매혹','맹격'].includes(selectedUnit.skill),burn=selectedUnit.skill==='천뢰',d=damage(selectedUnit,t,selectedUnit.skillPower);setUnits(us=>us.map(u=>u.id===selectedUnit.id?{...u,acted:true,rage:Math.min(100,u.rage+35)}:u.id===t.id?{...u,currentHp:Math.max(0,u.currentHp-d),status:burn?'burn':stun?'stun':u.status,statusTurns:burn||stun?2:u.statusTurns}:u));addLog(`${selectedUnit.name} ${selectedUnit.skill}! ${d} 피해`);setTarget(null);};
 const ultimate=()=>{if(!selectedUnit||selectedUnit.acted||turn!=='player'||selectedUnit.rage<100)return addLog('궁극기 게이지가 100이어야 합니다.');const enemies=units.filter(u=>u.team==='enemy'&&u.currentHp>0&&dist(selectedUnit,u)<=selectedUnit.range+1);if(!enemies.length)return addLog('궁극기 범위에 적이 없습니다.');setUnits(us=>us.map(u=>{if(u.id===selectedUnit.id)return{...u,acted:true,rage:0};if(u.team==='enemy'&&u.currentHp>0&&dist(selectedUnit,u)<=selectedUnit.range+1)return{...u,currentHp:Math.max(0,u.currentHp-damage(selectedUnit,u,selectedUnit.ultimatePower)),status:'stun',statusTurns:1};return u}));addLog(`${selectedUnit.name}의 궁극기 ${selectedUnit.ultimate}!`);};
 const endTurn=()=>{if(turn!=='player')return;setTurn('enemy');setTimeout(()=>{setUnits(prev=>{let next=prev.map(u=>u.team==='player'?{...u,acted:false,movePoints:u.move}:u);const targets=next.filter(u=>u.team==='player'&&u.currentHp>0);for(const e of next.filter(u=>u.team==='enemy'&&u.currentHp>0)){if(e.status==='stun'&&e.statusTurns>0)continue;const t=targets.slice().sort((a,b)=>dist(a,e)-dist(b,e))[0];if(t&&dist(e,t)<=e.range){const d=damage(e,t);const idx=next.findIndex(x=>x.id===t.id);if(idx>=0)next[idx]={...next[idx],currentHp:Math.max(0,next[idx].currentHp-d)};}else if(t){const step=[{x:e.x-1,y:e.y},{x:e.x,y:e.y-1},{x:e.x,y:e.y+1},{x:e.x+1,y:e.y}].filter(p=>p.x>=0&&p.x<W&&p.y>=0&&p.y<H&&terrain[p.y*W+p.x]!=='water'&&!next.some(u=>u.currentHp>0&&u.x===p.x&&u.y===p.y)).sort((a,b)=>dist(a,t)-dist(b,t))[0];if(step){const idx=next.findIndex(x=>x.id===e.id);if(idx>=0)next[idx]={...next[idx],x:step.x,y:step.y};}}}return next.map(u=>u.statusTurns>0?{...u,statusTurns:u.statusTurns-1,status:u.statusTurns===1?'none':u.status}:u);});setTurn('player');setTarget(null);},250);};
 const victory=units.length>0&&!units.some(u=>u.team==='enemy'&&u.currentHp>0),defeat=units.length>0&&!units.some(u=>u.team==='player'&&u.currentHp>0);
 if(victory){const reward=saveData.floor%10===0?1500:500;persist({...saveData,floor:saveData.floor+1,gold:saveData.gold+reward,gems:saveData.gems+(saveData.floor%10===0?30:5),materials:saveData.materials+(saveData.floor%10===0?30:10)});setUnits([]);setScreen('tower');addLog(`천탑 ${saveData.floor}층 돌파!`);}
 if(defeat){setUnits([]);setScreen('tower');addLog('전투 패배. 다시 도전하세요.');}
 const e=equipFor(selectedGeneral,saveData),lv=e.level;
 return <div style={{maxWidth:1050,margin:'0 auto',padding:16,fontFamily:'system-ui',color:'#e8edf7',background:'#101522',minHeight:'100vh'}}>
  <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'12px 8px',borderBottom:'1px solid #30394b'}}><div><h1 style={{margin:0,fontSize:22}}>무한삼국지: 천탑전기</h1><small>전술 SRPG MVP 0.9</small></div><div>Lv.{saveData.level} · 🪙 {saveData.gold} · 💎 {saveData.gems} · 🔧 {saveData.materials}</div></header>
  <nav style={{display:'flex',gap:6,flexWrap:'wrap',margin:'12px 0'}}>{[['home','홈'],['tower','천탑'],['generals','장수'],['inventory','장비'],['summon','모집']].map(([id,label])=><button key={id} onClick={()=>setScreen(id as any)} style={btn(screen===id)}>{label}</button>)}</nav>
  {screen==='home'&&<Panel title="천탑전기"><h2>무한의 탑에 도전하라</h2><p>7×6 격자 · 이동력 · 스킬 · 궁극기 · 상태이상 · 전용장비 옵션</p><button onClick={()=>setScreen('tower')} style={btn(true)}>천탑 입장 <ChevronRight size={16}/></button></Panel>}
  {screen==='tower'&&<Panel title={`천탑 ${saveData.floor}층`}><p>10층마다 보스전. 클리어 시 금화·보옥·강화재료를 획득합니다.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button onClick={startBattle} style={btn(true)}><Sword size={16}/> 전투 시작</button><button onClick={levelUp} style={btn(false)}>계정 레벨업 ({saveData.level*300}G)</button></div></Panel>}
  {screen==='generals'&&<Panel title="장수 관리"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:8}}>{generals.filter(g=>saveData.owned.includes(g.id)).map(g=>{const q=equipFor(g,saveData);const st=stat(g);return <button key={g.id} onClick={()=>setSelected(g.id)} style={{...card,outline:selected===g.id?'2px solid #8fb8ff':'none'}}><b>{g.name}</b><div>{g.title} · {g.role}</div><div>HP {st.hp} / ATK {st.atk}</div><div>전용장비 {g.equipment} +{q.level}</div><div>{rarityName(q.rarity)} · {q.equipped?'장착':'미장착'}</div></button>})}</div><EquipmentPanel g={selectedGeneral} e={e} lv={lv} enhance={enhance} reroll={reroll} toggleEquip={toggleEquip}/></Panel>}
  {screen==='inventory'&&<Panel title="전용장비 인벤토리"><p>보유 장수의 전용장비와 현재 옵션을 한눈에 확인합니다.</p><div style={{display:'grid',gap:8}}>{generals.filter(g=>saveData.owned.includes(g.id)).map(g=>{const q=equipFor(g,saveData);return <div key={g.id} style={card}><b>{g.name} · {g.equipment}</b><span>　+{q.level} {rarityName(q.rarity)} {q.equipped?'· 장착':''}</span><div style={{fontSize:13,marginTop:4}}>{q.level?`${optionNames[q.optionA]}${optionValue(q.optionA,q.level)} · ${optionNames[q.optionB]}${optionValue(q.optionB,q.level)}`:'강화 시 옵션이 활성화됩니다.'}</div></div>})}</div></Panel>}
  {screen==='summon'&&<Panel title="장수 모집"><p>30 보옥으로 미보유 장수를 확정 영입합니다.</p><button onClick={summon} style={btn(true)}><Gem size={16}/> 30 보옥 모집</button></Panel>}
  {screen==='battle'&&<Panel title={`천탑 ${saveData.floor}층 전투 · ${turn==='player'?'아군 턴':'적 턴'}`}><div style={{display:'grid',gridTemplateColumns:'repeat(7,1fr)',gap:4,maxWidth:700}}>{Array.from({length:W*H},(_,i)=>{const x=i%W,y=Math.floor(i/W),t=terrain[i],u=units.find(z=>z.x===x&&z.y===y&&z.currentHp>0);const movable=selectedUnit?.team==='player'&&!selectedUnit.acted&&turn==='player'&&t!=='water'&&dist(selectedUnit,{x,y})<=selectedUnit.movePoints&&!u;return <button key={i} onClick={()=>u?setSelected(u.id):moveUnit(x,y)} style={{height:70,padding:3,background:t==='forest'?'#1c3a2b':t==='hill'?'#4b3d28':t==='water'?'#18365b':t==='fort'?'#513d27':'#202938',border:movable?'2px solid #75aaff':'1px solid #364052',color:'#fff'}}>{u&&<><b style={{color:u.team==='player'?'#8fc1ff':'#ff9292'}}>{u.name}</b><div style={{fontSize:11}}>HP {u.currentHp}/{u.maxHp}</div><div style={{fontSize:10}}>R {u.rage} {u.status!=='none'&&`· ${u.status}`}</div></>}</button>})}</div><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:10}}><button onClick={basicAttack} style={btn(true)}>공격</button><button onClick={skill} style={btn(false)}>스킬</button><button onClick={ultimate} style={btn(false)}>궁극기</button><button onClick={endTurn} style={btn(false)}><RotateCcw size={16}/> 턴 종료</button></div><div style={card}><b>{selectedUnit?.name||'장수 선택'}</b> · MP {selectedUnit?.movePoints??'-'} · Rage {selectedUnit?.rage??'-'}<div style={{fontSize:13,marginTop:5}}>{log.map((x,i)=><div key={i}>{x}</div>)}</div></div></Panel>}
 </div>;
}
const btn=(active:boolean):React.CSSProperties=>({display:'inline-flex',alignItems:'center',gap:5,padding:'9px 12px',borderRadius:8,border:'1px solid #46536a',background:active?'#294d82':'#1a2231',color:'#fff',cursor:'pointer'});
const card:React.CSSProperties={padding:12,border:'1px solid #343e50',borderRadius:10,background:'#171e2c',textAlign:'left'};
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section style={{background:'#131a27',border:'1px solid #30394b',borderRadius:12,padding:16}}><h2 style={{marginTop:0}}>{title}</h2>{children}</section>}
function EquipmentPanel({g,e,lv,enhance,reroll,toggleEquip}:{g:General;e:EquipmentState;lv:number;enhance:()=>void;reroll:()=>void;toggleEquip:()=>void}){return <div style={{...card,marginTop:12}}><h3 style={{marginTop:0}}><Package size={17}/> {g.equipment} · +{lv} {rarityName(e.rarity)}</h3><div>장착 상태: {e.equipped?'장착':'미장착'}</div><div style={{margin:'8px 0'}}>옵션 ① {lv?`${optionNames[e.optionA]}${optionValue(e.optionA,lv)}`:'미활성'} · 옵션 ② {lv?`${optionNames[e.optionB]}${optionValue(e.optionB,lv)}`:'미활성'}</div><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button onClick={enhance} style={btn(true)}><Hammer size={16}/> 강화 ({(lv+1)*5} 재료)</button><button onClick={reroll} style={btn(false)}>옵션 재설정 (20)</button><button onClick={toggleEquip} style={btn(false)}><Shield size={16}/> {e.equipped?'해제':'장착'}</button></div></div>}
