import { useEffect, useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
import { Gem, Sword, Shield, Hammer, Package, Star, Users, RotateCcw } from 'lucide-react';
import { createMonsterEnemies } from './game/systems/monsterBattle';
import { getMonsterRegion } from './game/data/monsters';

type Faction='Wei'|'Shu'|'Wu'|'Warlords';
type Screen='home'|'tower'|'generals'|'inventory'|'summon'|'formation'|'battle';
type General={id:string;name:string;title:string;faction:Faction;role:string;hp:number;atk:number;range:number;move:number;skill:string;skillPower:number;ultimate:string;ultimatePower:number;equipment:string;grade:number;tsName:string;tsTitle:string};
type Equip={level:number;rarity:number;equipped:boolean;optionA:number;optionB:number};
type Save={floor:number;gold:number;gems:number;level:number;materials:number;owned:string[];equipment:Record<string,Equip>;stars:Record<string,number>;fragments:Record<string,number>;tsSkins:Record<string,boolean>;formation:string[]};
type Terrain='plain'|'forest'|'hill'|'water'|'fort';
type Status='none'|'stun'|'burn'|'slow'|'guard';
type Unit=General&{team:'player'|'enemy';x:number;y:number;currentHp:number;maxHp:number;acted:boolean;rage:number;buff:number;movePoints:number;status:Status;statusTurns:number};
const W=7,H=6,KEY='infinite-three-kingdoms-save-v2';
const G:General[]=[
['liu-bei','유비','인덕의 군주','Shu','지원',120,22,2,3,'인덕의 격려',0,'인덕의 대의',0,'쌍검',5,'유비·천룡','용덕의 군주'],['guan-yu','관우','미염공','Shu','전사',150,38,1,3,'청룡참',28,'청룡언월도',55,'청룡언월도',5,'관우·홍련','적토의 무장'],['zhang-fei','장비','만인지적','Shu','수호',190,28,1,2,'호통',0,'장판교 포효',34,'장팔사모',4,'장비·흑염','폭렬의 장군'],['zhao-yun','조운','상산의 용','Shu','기병',135,34,1,4,'용진',18,'칠진칠출',48,'용담창',5,'조운·은룡','은룡의 기사'],['zhuge-liang','제갈량','와룡','Shu','책사',95,30,3,2,'천뢰',24,'공성계',42,'백우선',5,'제갈량·성운','성운의 책사'],['cao-cao','조조','위무제','Wei','책사',125,29,2,3,'간웅의 명령',0,'위무의 천명',36,'의천검',5,'조조·흑금','패왕의 군주'],['xiahou-dun','하후돈','독안의 맹장','Wei','전사',160,35,1,3,'맹격',20,'독안참',45,'칠성도',4,'하후돈·백야','백야의 맹장'],['sun-quan','손권','강동의 호랑이','Wu','지원',130,27,2,3,'강동의 결의',0,'강동패왕',30,'벽옥검',4,'손권·벽옥','벽해의 군주'],['lu-bu','여포','천하무쌍','Warlords','기병',180,48,1,4,'천하무쌍',42,'신마난무',70,'방천화극',5,'여포·적월','적월의 마왕'],['diao-chan','초선','경국지색','Warlords','지원',90,24,2,3,'매혹',0,'폐월의 춤',32,'금선연',4,'초선·월화','월화의 무희']
].map(x=>({id:x[0],name:x[1],title:x[2],faction:x[3] as Faction,role:x[4],hp:+x[5],atk:+x[6],range:+x[7],move:+x[8],skill:x[9],skillPower:+x[10],ultimate:x[11],ultimatePower:+x[12],equipment:x[13],grade:+x[14],tsName:x[15],tsTitle:x[16]})) as General[];
const terrain:Terrain[]=Array.from({length:42},(_,i)=>i===17||i===18||i===24?'forest':i===11||i===12?'hill':i===26||i===27?'water':i===32?'fort':'plain');
const tCost:Record<Terrain,number>={plain:1,forest:2,hill:1,water:99,fort:1};
const equipDefault=()=>Object.fromEntries(G.map(g=>[g.id,{level:0,rarity:1,equipped:true,optionA:0,optionB:1}]));
const mapNum=()=>Object.fromEntries(G.map(g=>[g.id,0]));
const mapOne=()=>Object.fromEntries(G.map(g=>[g.id,1]));
const mapFalse=()=>Object.fromEntries(G.map(g=>[g.id,false]));
const base:Save={floor:1,gold:5000,gems:300,level:1,materials:120,owned:G.slice(0,5).map(g=>g.id),equipment:equipDefault(),stars:mapOne(),fragments:mapNum(),tsSkins:mapFalse(),formation:G.slice(0,5).map(g=>g.id)};
function load():Save{try{const r=JSON.parse(localStorage.getItem(KEY)||'{}');const owned=r.owned||base.owned;return {...base,...r,owned,formation:(r.formation||owned).filter((x:string)=>owned.includes(x)).slice(0,5),equipment:{...base.equipment,...r.equipment},stars:{...base.stars,...r.stars},fragments:{...base.fragments,...r.fragments},tsSkins:{...base.tsSkins,...r.tsSkins}}}catch{return base}}
const dist=(a:{x:number;y:number},b:{x:number;y:number})=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const rarity=(l:number)=>l>=15?5:l>=10?4:l>=5?3:l>=3?2:1;
const rName=(r:number)=>['','일반','고급','희귀','영웅','전설'][r];
const fragNeed=(s:number)=>s*20;
const optName=(k:number)=>['공격력 +','최대HP +','치명타 +','스킬 위력 +'][k];
const optVal=(k:number,l:number)=>k===0?l*2:k===1?l*5:k===2?Math.floor(l/2):l;
const weighted=(min=1)=>{const p=G.filter(g=>g.grade>=min);const w=p.map(g=>g.grade===5?5:g.grade===4?15:80);let n=Math.random()*w.reduce((a,b)=>a+b,0);for(let i=0;i<p.length;i++){n-=w[i];if(n<=0)return p[i]}return p[p.length-1]};
const towerInfo=(floor:number)=>{const boss=floor%10===0;return{boss,gold:boss?1500:500,gems:boss?30:5,materials:boss?30:10,modifier:boss?['보스: 광폭화','보스: 철벽','보스: 화염진'][Math.floor(floor/10-1)%3]:['일반','숲의 매복','고지의 전술'][floor%3]}};
export default function App(){
 const[save,setSave]=useState<Save>(load),[screen,setScreen]=useState<Screen>('home'),[selected,setSelected]=useState('guan-yu'),[target,setTarget]=useState<string|null>(null),[units,setUnits]=useState<Unit[]>([]),[turn,setTurn]=useState<'player'|'enemy'>('player'),[log,setLog]=useState<string[]>(['천탑 전투 준비 완료.']);
 const team=useMemo(()=>save.formation.map(id=>G.find(g=>g.id===id)).filter(Boolean) as General[],[save.formation]);
 const sg=G.find(g=>g.id===selected)||G[0];
 const eq=(g:General)=>save.equipment[g.id]||{level:0,rarity:1,equipped:true,optionA:0,optionB:1};
 const star=(g:General)=>save.stars[g.id]||1;
 const stats=(g:General)=>{const e=eq(g),l=e.equipped?e.level:0,m=1+.05*(star(g)-1);let hp=Math.floor((g.hp+(save.level-1)*12+l*10)*m),atk=Math.floor((g.atk+(save.level-1)*3+l*4)*m);[e.optionA,e.optionB].forEach(k=>{const v=optVal(k,l);if(k===0)atk+=v;if(k===1)hp+=v});return{hp,atk}};
 const su=units.find(u=>u.id===selected);const add=(s:string)=>setLog(v=>[s,...v].slice(0,8));const persist=(n:Save)=>{setSave(n);localStorage.setItem(KEY,JSON.stringify(n));};
 const resetGame=()=>{if(!window.confirm('게임 진행 상태를 모두 초기화할까요?\n보유 장수, 장비, 성급, 재화, 천탑 진행도가 모두 초기화됩니다.'))return;const fresh:Save={floor:1,gold:5000,gems:300,level:1,materials:120,owned:G.slice(0,5).map(g=>g.id),equipment:equipDefault(),stars:mapOne(),fragments:mapNum(),tsSkins:mapFalse(),formation:G.slice(0,5).map(g=>g.id)};persist(fresh);setScreen('home');setSelected(fresh.formation[0]||'guan-yu');setTarget(null);setUnits([]);setTurn('player');setLog(['게임 진행 상태가 초기화되었습니다.']);};
 const recruit=(count:number)=>{const cost=count*30;if(save.gems<cost)return add('보옥이 부족합니다.');let owned=[...save.owned],fr={...save.fragments};const out:string[]=[];for(let i=0;i<count;i++){const g=weighted(count===10&&i===9?4:1);if(owned.includes(g.id)){fr[g.id]=(fr[g.id]||0)+10;out.push(`${g.name} 조각+10`)}else{owned.push(g.id);out.push(`${g.name} 영입`)}}persist({...save,gems:save.gems-cost,owned,fragments:fr,formation:save.formation.length?save.formation:owned.slice(0,5)});add(out.join(' / '));};
 const recruitEquip=()=>{if(save.gems<20)return add('장비 소환에 20 보옥이 필요합니다.');const g=G[Math.floor(Math.random()*G.length)],e=save.equipment[g.id]||{level:0,rarity:1,equipped:true,optionA:0,optionB:1};const bonus=1+Math.floor(Math.random()*4);const n={...e,level:Math.min(20,e.level+bonus),rarity:rarity(Math.min(20,e.level+bonus)),optionA:Math.floor(Math.random()*4),optionB:Math.floor(Math.random()*4)};if(n.optionA===n.optionB)n.optionB=(n.optionB+1)%4;persist({...save,gems:save.gems-20,materials:save.materials+10,equipment:{...save.equipment,[g.id]:n}});add(`${g.name} 전용장비 ${rName(n.rarity)} 획득 · +${n.level}`)};
 const start=()=>{if(!team.length)return add('편성을 먼저 구성하세요.');const ps=team.map((g,i)=>{const s=stats(g);return{...g,...s,maxHp:s.hp,currentHp:s.hp,team:'player' as const,x:i%3,y:5-Math.floor(i/3),acted:false,rage:0,buff:0,movePoints:g.move,status:'none' as Status,statusTurns:0}});const info=towerInfo(save.floor);const region=getMonsterRegion(save.floor);const es=createMonsterEnemies(save.floor);setUnits([...ps,...es]);setSelected(team[0].id);setTarget(null);setTurn('player');setLog([`천탑 ${save.floor}층 · ${region.name} · ${info.modifier}${info.boss?' · BOSS':''}`]);setScreen('battle');};
 const damage=(a:Unit,b:Unit,bonus=0)=>Math.max(1,a.atk+a.buff+bonus+(terrain[b.y*W+b.x]==='fort'?8:terrain[b.y*W+b.x]==='hill'?4:0)-Math.floor(b.maxHp*.08)-(b.status==='guard'?8:0));
 const move=(x:number,y:number)=>{if(!su||su.team!=='player'||su.acted||turn!=='player')return;const c=terrain[y*W+x],d=dist(su,{x,y});if(c==='water'||d===0||d>su.movePoints)return;if(units.some(u=>u.currentHp>0&&u.x===x&&u.y===y))return;setUnits(us=>us.map(u=>u.id===su.id?{...u,x,y,movePoints:u.movePoints-tCost[c]}:u))};
 const choose=(u:Unit)=>{if(u.team==='enemy'&&su?.team==='player')setTarget(u.id);else if(u.team==='player'){setSelected(u.id);setTarget(null)}};
 const attack=(power=0)=>{if(!su||su.team!=='player'||su.acted||turn!=='player')return;const t=units.find(u=>u.id===target&&u.team==='enemy'&&u.currentHp>0);if(!t||dist(su,t)>su.range)return add('공격 대상이 필요합니다.');const d=damage(su,t,power);setUnits(us=>us.map(u=>u.id===su.id?{...u,acted:true,rage:Math.min(100,u.rage+25)}:u.id===t.id?{...u,currentHp:Math.max(0,u.currentHp-d),rage:Math.min(100,u.rage+15)}:u));add(`${su.name} → ${t.name} ${d} 피해`);setTarget(null)};
 const skill=()=>{if(!su||su.acted)return;if(su.skill==='인덕의 격려'||su.skill==='강동의 결의'){setUnits(us=>us.map(u=>u.team==='player'&&u.currentHp>0?{...u,buff:u.buff+(u.id===su.id?3:8),status:'guard',statusTurns:1}:u.id===su.id?{...u,acted:true}:u));add(`${su.skill} 발동`);return}if(su.skill==='간웅의 명령'){setUnits(us=>us.map(u=>u.team==='enemy'&&u.currentHp>0?{...u,atk:Math.max(1,u.atk-6),status:'slow',statusTurns:1}:u.id===su.id?{...u,acted:true}:u));add('적 전체 약화');return}attack(su.skillPower)};
 const endTurn=()=>{setTurn('enemy');setUnits(us=>us.map(u=>u.team==='player'?{...u,acted:false,movePoints:u.move}:u))};
 useEffect(()=>{if(turn!=='enemy'||!units.length)return;const timer=setTimeout(()=>{let next=[...units];for(const e of next.filter(u=>u.team==='enemy'&&u.currentHp>0)){const p=next.filter(u=>u.team==='player'&&u.currentHp>0).sort((a,b)=>dist(e,a)-dist(e,b))[0];if(!p)break;const d=damage(e,p);if(dist(e,p)<=e.range){p.currentHp=Math.max(0,p.currentHp-d);add(`${e.name}의 공격 ${d}`)}else{const nx=e.x+(p.x>e.x?1:p.x<e.x?-1:0),ny=e.y+(p.y>e.y?1:p.y<e.y?-1:0);if(!next.some(u=>u.currentHp>0&&u.x===nx&&u.y===ny))e.x=nx,e.y=ny}}setUnits(next.map(u=>u.team==='player'?{...u,acted:false,movePoints:u.move}:u));setTurn('player')},450);return()=>clearTimeout(timer)},[turn]);
 useEffect(()=>{if(!units.length)return;const p=units.filter(u=>u.team==='player'&&u.currentHp>0),e=units.filter(u=>u.team==='enemy'&&u.currentHp>0);if(!e.length){const i=towerInfo(save.floor);persist({...save,floor:Math.min(100,save.floor+1),gold:save.gold+i.gold,gems:save.gems+i.gems,materials:save.materials+i.materials});add(`천탑 ${save.floor}층 클리어! +${i.gold}금화 +${i.gems}보옥`);setUnits([]);setScreen('tower')}else if(!p.length){add('전투 패배');setUnits([]);setScreen('tower')}},[units]);
 const levelUp=()=>{const c=save.level*300;if(save.gold<c)return add(`금화 부족 · ${c} 금화 필요`);persist({...save,level:save.level+1,gold:save.gold-c});add(`계정 레벨 ${save.level} → ${save.level+1} · 금화 -${c}`)};
 const enhance=()=>{const e=eq(sg),cost=(e.level+1)*5;if(e.level>=20)return;if(save.materials<cost)return add('강화 재료 부족');const l=e.level+1;persist({...save,materials:save.materials-cost,equipment:{...save.equipment,[sg.id]:{...e,level:l,rarity:rarity(l)}}})};
 const breakthrough=()=>{const s=star(sg),need=fragNeed(s);if(s>=6)return;if((save.fragments[sg.id]||0)<need)return add(`${need}개 조각 필요`);persist({...save,stars:{...save.stars,[sg.id]:s+1},fragments:{...save.fragments,[sg.id]:(save.fragments[sg.id]||0)-need}})};
 const unlockTS=()=>{if(save.tsSkins[sg.id])return add('이미 보유');if(save.gems<100)return add('100 보옥 필요');persist({...save,gems:save.gems-100,tsSkins:{...save.tsSkins,[sg.id]:true}})};
 const toggleForm=(id:string)=>{let f=[...save.formation];if(f.includes(id))f=f.filter(x=>x!==id);else if(f.length<5)f.push(id);else return add('최대 5명');persist({...save,formation:f})};
 const nav=(s:Screen)=>setScreen(s);
 const card:CSSProperties={background:'#141923',border:'1px solid #2a3345',borderRadius:12,padding:12};const btn:CSSProperties={background:'#202a3c',color:'#fff',border:'1px solid #3a4760',borderRadius:8,padding:'9px 12px',cursor:'pointer'};
 return <div style={{minHeight:'100vh',background:'#0b0f16',color:'#edf2f7',fontFamily:'system-ui',padding:16}}><div style={{maxWidth:1100,margin:'auto'}}>
 <header style={{...card,display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12}}><div><b style={{fontSize:22}}>무한삼국지: 천탑전기</b><div style={{fontSize:12,color:'#9aa6b8'}}>MVP 1.3 · 삼국지 장수 vs 판타지 몬스터 · 1~100층 천탑</div></div><div style={{display:'flex',gap:12}}><span>💰 {save.gold}</span><span><Gem size={15}/> {save.gems}</span><span>🧱 {save.materials}</span></div></header>
 <nav style={{display:'flex',gap:6,flexWrap:'wrap',marginBottom:12}}>{[['home','홈'],['tower','천탑'],['generals','장수'],['formation','편성'],['inventory','장비'],['summon','소환']].map(([k,v])=><button key={k} style={btn} onClick={()=>nav(k as Screen)}>{v}</button>)}</nav>
 {screen==='home'&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:12}}><div style={card}><h2>천탑 {save.floor}/100</h2><p>10층마다 해당 몬스터 지역의 보스가 등장합니다.</p><button style={btn} onClick={start}>전투 시작</button></div><div style={card}><h3>계정 Lv.{save.level}</h3><p>다음 레벨 비용 {save.level*300} 금화</p><button style={btn} onClick={levelUp}>레벨업</button></div><div style={card}><h3>현재 편성</h3>{team.map(g=><div key={g.id}>★{star(g)} {g.name}</div>)}</div><div style={{...card,border:'1px solid #5a2f36'}}><h3><RotateCcw size={17}/> 게임 데이터</h3><p style={{fontSize:13,color:'#9aa6b8'}}>천탑 진행도, 장수, 장비, 성급, 재화와 편성을 초기 상태로 되돌립니다.</p><button style={{...btn,border:'1px solid #8a4650'}} onClick={resetGame}>게임 진행 상태 초기화</button></div></div>}
 {screen==='tower'&&<div style={{...card}}><h2>천탑 1~100층</h2><div style={{display:'grid',gridTemplateColumns:'repeat(10,1fr)',gap:6}}>{Array.from({length:100},(_,i)=>i+1).map(f=><button key={f} disabled={f>save.floor} style={{...btn,padding:8,opacity:f>save.floor?.4:1}} onClick={()=>{if(f===save.floor)start()}}>{f}{f%10===0?' 👑':''}</button>)}</div><p style={{marginTop:12}}>현재 층: {save.floor} · 지역: {getMonsterRegion(save.floor).name} · {getMonsterRegion(save.floor).description} · 패턴: {towerInfo(save.floor).modifier}</p></div>}
 {screen==='generals'&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:12}}>{G.filter(g=>save.owned.includes(g.id)).map(g=><div key={g.id} style={card} onClick={()=>setSelected(g.id)}><h3>★{star(g)} {g.name}</h3><p>{g.title} · {g.role}</p><p>HP {stats(g).hp} / ATK {stats(g).atk}</p><p>조각 {save.fragments[g.id]||0}/{star(g)<6?fragNeed(star(g)):0}</p><button style={btn} onClick={breakthrough}>돌파</button> <button style={btn} onClick={unlockTS}>{save.tsSkins[g.id]?'TS 보유':'TS 100💎'}</button></div>)}</div>}
 {screen==='formation'&&<div style={card}><h2>전투 편성 {save.formation.length}/5</h2>{G.filter(g=>save.owned.includes(g.id)).map(g=><div key={g.id} style={{display:'flex',justifyContent:'space-between',padding:8,borderBottom:'1px solid #252d3b'}}><span>★{star(g)} {g.name}</span><button style={btn} onClick={()=>toggleForm(g.id)}>{save.formation.includes(g.id)?'제외':'편성'}</button></div>)}</div>}
 {screen==='inventory'&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:12}}>{G.filter(g=>save.owned.includes(g.id)).map(g=>{const e=eq(g);return <div key={g.id} style={card}><h3>{g.name} · {g.equipment}</h3><b>{rName(e.rarity)} +{e.level}</b><p>{optName(e.optionA)} {optVal(e.optionA,e.level)} / {optName(e.optionB)} {optVal(e.optionB,e.level)}</p><button style={btn} onClick={()=>{setSelected(g.id);enhance()}}>강화</button></div>})}</div>}
 {screen==='summon'&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div style={card}><h2>장수 소환</h2><p>1회 30 보옥 · 10회 300 보옥</p><button style={btn} onClick={()=>recruit(1)}>1회 소환</button> <button style={btn} onClick={()=>recruit(10)}>10회 소환</button></div><div style={card}><h2>전용장비 소환</h2><p>20 보옥 · 기존 장비가 있으면 강화 단계와 옵션이 갱신됩니다.</p><button style={btn} onClick={recruitEquip}><Hammer size={16}/> 장비 소환</button></div></div>}
 {screen==='battle'&&<div><div style={{...card,display:'flex',justifyContent:'space-between'}}><div><b>천탑 {save.floor}층</b> · {getMonsterRegion(save.floor).name} · {towerInfo(save.floor).modifier}</div><span style={{fontSize:13,color:'#9aa6b8'}}>수동 전투</span></div><div style={{display:'grid',gridTemplateColumns:'repeat(7,1fr)',gap:5,margin:'12px 0'}}>{Array.from({length:42},(_,i)=>{const x=i%7,y=Math.floor(i/7),u=units.find(q=>q.x===x&&q.y===y&&q.currentHp>0);return <button key={i} onClick={()=>u?choose(u):move(x,y)} style={{minHeight:72,border:'1px solid #30394a',borderRadius:8,background:terrain[i]==='water'?'#17263a':terrain[i]==='forest'?'#172a22':terrain[i]==='hill'?'#2a2418':'#151b25',color:'#fff'}}>{u&&<><div>{u.team==='player'?'🟦':'🟥'} {u.name}</div><div style={{fontSize:11}}>HP {u.currentHp}/{u.maxHp}</div>{target===u.id&&<b>🎯</b>}</>}</button>})}</div><div style={{...card,display:'flex',gap:8,flexWrap:'wrap'}}><b>{su?.name||'선택 없음'}</b><button style={btn} onClick={()=>attack()}>기본공격</button><button style={btn} onClick={skill}>스킬</button><button style={btn} onClick={endTurn}>턴 종료</button></div><div style={{...card,marginTop:12}}>{log.map((x,i)=><div key={i}>{x}</div>)}</div></div>}
 </div></div>;
}