import { useEffect, useMemo, useState } from 'react';
import type { CSSProperties, ReactNode } from 'react';
import { ChevronRight, RotateCcw, Sword, Shield, Hammer, Gem, Package, Star, Users } from 'lucide-react';

type Faction='Wei'|'Shu'|'Wu'|'Warlords';
type General={id:string;name:string;title:string;faction:Faction;role:string;hp:number;atk:number;range:number;move:number;skill:string;skillPower:number;ultimate:string;ultimatePower:number;equipment:string;grade:number;tsName:string;tsTitle:string;tsColor:string};
type Status='none'|'stun'|'burn'|'slow'|'guard';
type Terrain='plain'|'forest'|'hill'|'water'|'fort';
type EquipmentState={level:number;rarity:number;equipped:boolean;optionA:number;optionB:number};
type SaveData={floor:number;gold:number;gems:number;level:number;equipLevel:number;owned:string[];materials:number;equipment:Record<string,EquipmentState>;stars:Record<string,number>;fragments:Record<string,number>;tsSkins:Record<string,boolean>;formation:string[]};
type Unit=General&{team:'player'|'enemy';x:number;y:number;currentHp:number;maxHp:number;acted:boolean;rage:number;buff:number;movePoints:number;status:Status;statusTurns:number};
const W=7,H=6,saveKey='infinite-three-kingdoms-save-v2';
const terrain:Terrain[]=Array.from({length:42},(_,i)=>i===17||i===18||i===24?'forest':i===11||i===12?'hill':i===26||i===27?'water':i===32?'fort':'plain');
const terrainCost:Record<Terrain,number>={plain:1,forest:2,hill:1,water:99,fort:1};
const generals:General[]=[
['liu-bei','유비','인덕의 군주','Shu','지원',120,22,2,3,'인덕의 격려',0,'인덕의 대의',0,'쌍검',5,'유비·천룡','용덕의 군주','blue'],
['guan-yu','관우','미염공','Shu','전사',150,38,1,3,'청룡참',28,'청룡언월도',55,'청룡언월도',5,'관우·홍련','적토의 무장','red'],
['zhang-fei','장비','만인지적','Shu','수호',190,28,1,2,'호통',0,'장판교 포효',34,'장팔사모',4,'장비·흑염','폭렬의 장군','orange'],
['zhao-yun','조운','상산의 용','Shu','기병',135,34,1,4,'용진',18,'칠진칠출',48,'용담창',5,'조운·은룡','은룡의 기사','silver'],
['zhuge-liang','제갈량','와룡','Shu','책사',95,30,3,2,'천뢰',24,'공성계',42,'백우선',5,'제갈량·성운','성운의 책사','violet'],
['cao-cao','조조','위무제','Wei','책사',125,29,2,3,'간웅의 명령',0,'위무의 천명',36,'의천검',5,'조조·흑금','패왕의 군주','black'],
['xiahou-dun','하후돈','독안의 맹장','Wei','전사',160,35,1,3,'맹격',20,'독안참',45,'칠성도',4,'하후돈·백야','백야의 맹장','white'],
['sun-quan','손권','강동의 호랑이','Wu','지원',130,27,2,3,'강동의 결의',0,'강동패왕',30,'벽옥검',4,'손권·벽옥','벽해의 군주','cyan'],
['lu-bu','여포','천하무쌍','Warlords','기병',180,48,1,4,'천하무쌍',42,'신마난무',70,'방천화극',5,'여포·적월','적월의 마왕','crimson'],
['diao-chan','초선','경국지색','Warlords','지원',90,24,2,3,'매혹',0,'폐월의 춤',32,'금선연',4,'초선·월화','월화의 무희','pink']
].map(x=>({id:x[0] as string,name:x[1] as string,title:x[2] as string,faction:x[3] as Faction,role:x[4] as string,hp:x[5] as number,atk:x[6] as number,range:x[7] as number,move:x[8] as number,skill:x[9] as string,skillPower:x[10] as number,ultimate:x[11] as string,ultimatePower:x[12] as number,equipment:x[13] as string,grade:x[14] as number,tsName:x[15] as string,tsTitle:x[16] as string,tsColor:x[17] as string}));
const defaultEquip=():Record<string,EquipmentState>=>Object.fromEntries(generals.map(g=>[g.id,{level:0,rarity:1,equipped:true,optionA:0,optionB:1}]));
const defaultStars=():Record<string,number>=>Object.fromEntries(generals.map(g=>[g.id,1]));
const defaultFragments=():Record<string,number>=>Object.fromEntries(generals.map(g=>[g.id,0]));
const defaultTS=():Record<string,boolean>=>Object.fromEntries(generals.map(g=>[g.id,false]));
const defaultSave:SaveData={floor:1,gold:5000,gems:300,level:1,equipLevel:0,owned:generals.slice(0,5).map(g=>g.id),materials:120,equipment:defaultEquip(),stars:defaultStars(),fragments:defaultFragments(),tsSkins:defaultTS(),formation:generals.slice(0,5).map(g=>g.id)};
const loadSave=():SaveData=>{try{const r=JSON.parse(localStorage.getItem(saveKey)||'{}'),e=defaultEquip(),s=defaultStars(),f=defaultFragments(),t=defaultTS();for(const g of generals){const q=r.equipment?.[g.id];if(q)e[g.id]={level:q.level||0,rarity:q.rarity||1,equipped:q.equipped!==false,optionA:q.optionA??0,optionB:q.optionB??1};else if(r.equipLevel)e[g.id]={level:r.equipLevel,rarity:1,equipped:true,optionA:0,optionB:1};s[g.id]=Math.max(1,r.stars?.[g.id]||1);f[g.id]=r.fragments?.[g.id]||0;t[g.id]=r.tsSkins?.[g.id]||false}const owned=r.owned||defaultSave.owned;return{...defaultSave,...r,owned,equipment:e,stars:s,fragments:f,tsSkins:t,formation:(r.formation||owned).filter((id:string)=>owned.includes(id)).slice(0,5),materials:r.materials??120}}catch{return defaultSave}};
const dist=(a:{x:number;y:number},b:{x:number;y:number})=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const rarityName=(r:number)=>['','일반','고급','희귀','영웅','전설'][r]||'전설';
const rarityFor=(l:number)=>l>=15?5:l>=10?4:l>=5?3:l>=3?2:1;
const optionNames=['공격력 +','최대HP +','치명타 +','스킬 위력 +'];
const optionValue=(k:number,l:number)=>k===0?l*2:k===1?l*5:k===2?Math.floor(l/2):l;
const fragmentNeed=(star:number)=>star*20;
const weightedPick=(pool:General[],minGrade=1)=>{const a=pool.filter(g=>g.grade>=minGrade);const src=a.length?a:pool;const weights=src.map(g=>g.grade===5?5:g.grade===4?15:80);let n=Math.random()*weights.reduce((x,y)=>x+y,0);for(let i=0;i<src.length;i++){n-=weights[i];if(n<=0)return src[i]}return src[src.length-1]};

export default function App(){
 const[save,setSave]=useState<SaveData>(()=>loadSave()),[screen,setScreen]=useState<'home'|'tower'|'generals'|'inventory'|'summon'|'formation'|'battle'>('home'),[selected,setSelected]=useState('guan-yu'),[target,setTarget]=useState<string|null>(null),[units,setUnits]=useState<Unit[]>([]),[turn,setTurn]=useState<'player'|'enemy'>('player'),[log,setLog]=useState(['천탑 전투 준비 완료.']);
 const team=useMemo(()=>save.formation.map(id=>generals.find(g=>g.id===id)).filter(Boolean) as General[],[save.formation]);
 const sg=generals.find(g=>g.id===selected)||generals[0];
 const eq=(g:General)=>save.equipment[g.id]||{level:0,rarity:1,equipped:true,optionA:0,optionB:1};
 const star=(g:General)=>save.stars[g.id]||1;
 const stats=(g:General)=>{const e=eq(g),l=e.equipped?e.level:0,sm=1+0.05*(star(g)-1);let hp=Math.floor((g.hp+(save.level-1)*12+l*10)*sm),atk=Math.floor((g.atk+(save.level-1)*3+l*4)*sm);for(const k of[e.optionA,e.optionB]){const v=optionValue(k,l);if(k===0)atk+=v;if(k===1)hp+=v}return{hp,atk}};
 const selectedUnit=units.find(u=>u.id===selected);const addLog=(s:string)=>setLog(v=>[s,...v].slice(0,8));const persist=(n:SaveData)=>{setSave(n);localStorage.setItem(saveKey,JSON.stringify(n));};
 const enhance=()=>{const e=eq(sg);if(e.level>=20)return addLog('최대 강화입니다.');const cost=(e.level+1)*5;if(save.materials<cost)return addLog(`강화 재료 부족: ${cost}`);const l=e.level+1;persist({...save,materials:save.materials-cost,equipment:{...save.equipment,[sg.id]:{...e,level:l,rarity:rarityFor(l)}}});addLog(`${sg.name} ${sg.equipment} +${l} 강화!`)};
 const reroll=()=>{const e=eq(sg);if(e.level<3)return addLog('+3부터 옵션 재설정 가능');if(save.materials<20)return addLog('옵션석 부족');let a=Math.floor(Math.random()*4),b=Math.floor(Math.random()*4);if(a===b)b=(b+1)%4;persist({...save,materials:save.materials-20,equipment:{...save.equipment,[sg.id]:{...e,optionA:a,optionB:b}}});addLog('전용장비 옵션 재설정 완료');};
 const toggle=()=>{const e=eq(sg);persist({...save,equipment:{...save.equipment,[sg.id]:{...e,equipped:!e.equipped}}});};
 const breakthrough=()=>{const s=star(sg),need=fragmentNeed(s);if(s>=6)return addLog('★6 최대 등급입니다.');if((save.fragments[sg.id]||0)<need)return addLog(`장수 조각 부족: ${need}개 필요`);persist({...save,fragments:{...save.fragments,[sg.id]:(save.fragments[sg.id]||0)-need},stars:{...save.stars,[sg.id]:s+1}});addLog(`${sg.name} ★${s+1} 돌파 완료!`)};
 const levelUp=()=>{const c=save.level*300;if(save.gold<c)return addLog(`금화 부족: ${c}`);persist({...save,level:save.level+1});};
 const recruit=(count:number)=>{const cost=30*count;if(save.gems<cost)return addLog('보옥 부족');let owned=[...save.owned],fragments={...save.fragments},result:string[]=[];for(let i=0;i<count;i++){const g=weightedPick(generals,count===10&&i===count-1?4:1);if(owned.includes(g.id)){fragments[g.id]=(fragments[g.id]||0)+10;result.push(`${g.name} 조각 +10`)}else{owned.push(g.id);result.push(`${g.name} 영입`);}}const formation=save.formation.length?save.formation:[...owned.slice(0,5)];persist({...save,gems:save.gems-cost,owned,fragments,formation:formation.filter(id=>owned.includes(id)).slice(0,5)});addLog(count===10?`10회 모집 완료 · ${result.join(' / ')}`:result[0]);};
 const toggleFormation=(id:string)=>{if(!save.owned.includes(id))return;let f=[...save.formation];if(f.includes(id))f=f.filter(x=>x!==id);else if(f.length<5)f.push(id);else return addLog('편성은 최대 5명입니다.');persist({...save,formation:f});};
 const moveFormation=(id:string,dir:number)=>{const i=save.formation.indexOf(id),j=i+dir;if(i<0||j<0||j>=save.formation.length)return;const f=[...save.formation];[f[i],f[j]]=[f[j],f[i]];persist({...save,formation:f});};
 const unlockTS=()=>{if(!save.owned.includes(sg.id))return;if(save.tsSkins[sg.id])return addLog('이미 TS 스킨을 보유하고 있습니다.');if(save.gems<100)return addLog('TS 스킨 해금에는 100 보옥이 필요합니다.');persist({...save,gems:save.gems-100,tsSkins:{...save.tsSkins,[sg.id]:true}});addLog(`${sg.name}의 TS 스킨 「${sg.tsName}」 해금!`)};
 const start=()=>{if(team.length===0)return addLog('편성된 장수가 없습니다.');const ps=team.map((g,i)=>{const s=stats(g);return{...g,...s,maxHp:s.hp,currentHp:s.hp,team:'player' as const,x:i%3,y:5-Math.floor(i/3),acted:false,rage:0,buff:0,movePoints:g.move,status:'none' as Status,statusTurns:0}});const ids=save.floor%10===0?['lu-bu','xiahou-dun','cao-cao']:['xiahou-dun','zhang-fei','sun-quan'];const es=ids.map((id,i)=>{const g=generals.find(x=>x.id===id)!;const s=stats(g);return{...g,...s,maxHp:s.hp+save.floor*5,currentHp:s.hp+save.floor*5,team:'enemy' as const,x:4+i%2,y:i+1,acted:false,rage:0,buff:0,movePoints:g.move,status:'none' as Status,statusTurns:0}});setUnits([...ps,...es]);setSelected(team[0].id);setTurn('player');setTarget(null);setLog([`천탑 ${save.floor}층 전투 시작`]);setScreen('battle');};
 const damage=(a:Unit,b:Unit,bonus=0)=>Math.max(1,a.atk+a.buff+bonus+(terrain[b.y*W+b.x]==='fort'?8:terrain[b.y*W+b.x]==='hill'?4:0)-Math.floor(b.maxHp*.08)-(b.status==='guard'?8:0));
 const move=(x:number,y:number)=>{if(!selectedUnit||selectedUnit.team!=='player'||selectedUnit.acted||turn!=='player')return;const c=terrain[y*W+x],d=dist(selectedUnit,{x,y});if(c==='water')return addLog('수로 이동 불가');if(d===0||d>selectedUnit.movePoints)return addLog(`이동력 부족: ${selectedUnit.movePoints}`);if(units.some(u=>u.currentHp>0&&u.x===x&&u.y===y))return addLog('점유된 칸');setUnits(us=>us.map(u=>u.id===selectedUnit.id?{...u,x,y,movePoints:u.movePoints-terrainCost[c]}:u));};
 const selectCell=(u:Unit|null)=>{if(!u)return;if(u.team==='enemy'&&selectedUnit?.team==='player'&&turn==='player'){setTarget(u.id);return}if(u.team==='player'){setSelected(u.id);setTarget(null)}};
 const attack=()=>{if(!selectedUnit||selectedUnit.acted||turn!=='player')return;const t=units.find(u=>u.id===target&&u.team==='enemy'&&u.currentHp>0);if(!t||dist(selectedUnit,t)>selectedUnit.range)return addLog('공격 대상 선택');const d=damage(selectedUnit,t);setUnits(us=>us.map(u=>u.id===selectedUnit.id?{...u,acted:true,rage:Math.min(100,u.rage+25)}:u.id===t.id?{...u,currentHp:Math.max(0,u.currentHp-d),rage:Math.min(100,u.rage+15)}:u));addLog(`${selectedUnit.name} 기본 공격 ${d}`);setTarget(null)};
 const skill=()=>{if(!selectedUnit||selectedUnit.acted||turn!=='player')return;const t=units.find(u=>u.id===target&&u.team==='enemy'&&u.currentHp>0);if(selectedUnit.skill==='인덕의 격려'||selectedUnit.skill==='강동의 결의'){setUnits(us=>us.map(u=>u.team==='player'&&u.currentHp>0?{...u,buff:u.buff+(selectedUnit.skill==='인덕의 격려'&&u.id!==selectedUnit.id?8:3),status:'guard',statusTurns:1}:u.id===selectedUnit.id?{...u,acted:true,rage:Math.min(100,u.rage+20)}:u));addLog('아군 지원 효과 발동');return}if(selectedUnit.skill==='간웅의 명령'){setUnits(us=>us.map(u=>u.team==='enemy'&&u.currentHp>0?{...u,atk:Math.max(1,u.atk-6),status:'slow',statusTurns:1}:u.id===selectedUnit.id?{...u,acted:true,rage:Math.min(100,u.rage+20)}:u));addLog('적 전체 약화');return}if(!t||dist(selectedUnit,t)>selectedUnit.range+1)return addLog('스킬 대상 선택');const stun=['호통','매혹','맹격'].includes(selectedUnit.skill),burn=selectedUnit.skill==='천뢰',d=damage(selectedUnit,t,selectedUnit.skillPower);setUnits(us=>us.map(u=>u.id===selectedUnit.id?{...u,acted:true,rage:Math.min(100,u.rage+35)}:u.id===t.id?{...u,currentHp:Math.max(0,u.currentHp-d),status:burn?'burn':stun?'stun':u.status,statusTurns:burn||stun?2:u.statusTurns}:u));addLog(`${selectedUnit.name} ${selectedUnit.skill} ${d}`);setTarget(null)};
 const ultimate=()=>{if(!selectedUnit||selectedUnit.acted||turn!=='player'||selectedUnit.rage<100)return addLog('Rage 100 필요');const es=units.filter(u=>u.team==='enemy'&&u.currentHp>0&&dist(selectedUnit,u)<=selectedUnit.range+1);if(!es.length)return addLog('궁극기 범위 없음');setUnits(us=>us.map(u=>u.id===selectedUnit.id?{...u,acted:true,rage:0}:u.team==='enemy'&&u.currentHp>0&&dist(selectedUnit,u)<=selectedUnit.range+1?{...u,currentHp:Math.max(0,u.currentHp-damage(selectedUnit,u,selectedUnit.ultimatePower)),status:'stun',statusTurns:1}:u));addLog(`${selectedUnit.name} 궁극기 ${selectedUnit.ultimate}`)};
 const endTurn=()=>{if(turn!=='player')return;setTurn('enemy');setTimeout(()=>{setUnits(prev=>{let n=prev.map(u=>u.team==='player'?{...u,acted:false,movePoints:u.move}:u);const ps=n.filter(u=>u.team==='player'&&u.currentHp>0);for(const e of n.filter(u=>u.team==='enemy'&&u.currentHp>0)){if(e.status==='stun')continue;const t=ps.slice().sort((a,b)=>dist(a,e)-dist(b,e))[0];if(t&&dist(e,t)<=e.range){const d=damage(e,t),i=n.findIndex(x=>x.id===t.id);n[i]={...n[i],currentHp:Math.max(0,n[i].currentHp-d)}}else if(t){const p=[{x:e.x-1,y:e.y},{x:e.x+1,y:e.y},{x:e.x,y:e.y-1},{x:e.x,y:e.y+1}].filter(p=>p.x>=0&&p.x<W&&p.y>=0&&p.y<H&&terrain[p.y*W+p.x]!=='water'&&!n.some(u=>u.currentHp>0&&u.x===p.x&&u.y===p.y)).sort((a,b)=>dist(a,t)-dist(b,t))[0];if(p){const i=n.findIndex(x=>x.id===e.id);n[i]={...n[i],x:p.x,y:p.y}}}}return n.map(u=>u.statusTurns>0?{...u,statusTurns:u.statusTurns-1,status:u.statusTurns===1?'none':u.status}:u)});setTurn('player');setTarget(null)},220)};
 const victory=units.length>0&&!units.some(u=>u.team==='enemy'&&u.currentHp>0),defeat=units.length>0&&!units.some(u=>u.team==='player'&&u.currentHp>0);
 useEffect(()=>{if(!victory&&!defeat)return;if(victory){const boss=save.floor%10===0;persist({...save,floor:save.floor+1,gold:save.gold+(boss?1500:500),gems:save.gems+(boss?30:5),materials:save.materials+(boss?30:10)});addLog(`천탑 ${save.floor}층 돌파!`)}else addLog('전투 패배');setUnits([]);setScreen('tower')},[victory,defeat]);
 const q=eq(sg);
 return <div style={app}><header style={header}><div><h1 style={{margin:0,fontSize:22}}>무한삼국지: 천탑전기</h1><small>MVP 1.1 · 성장 · 전용장비 · TS 스킨 · 편성</small></div><div>Lv.{save.level} · 🪙{save.gold} · 💎{save.gems} · 🔧{save.materials}</div></header><nav style={nav}>{[['home','홈'],['tower','천탑'],['generals','장수'],['formation','편성'],['inventory','장비'],['summon','모집']].map(([id,l])=><button key={id} onClick={()=>setScreen(id as any)} style={btn(screen===id)}>{l}</button>)}</nav>
 {screen==='home'&&<Panel title="천탑전기"><h2>무한의 탑에 도전하라</h2><p>7×6 격자 전투 · 이동력 · 스킬 · 궁극기 · 상태이상 · 전용장비 · ★성장</p><button style={btn(true)} onClick={()=>setScreen('tower')}>천탑 입장 <ChevronRight size={16}/></button></Panel>}
 {screen==='tower'&&<Panel title={`천탑 ${save.floor}층`}><p>10층마다 보스. 클리어 보상으로 강화 재료와 보옥을 획득합니다.</p><p>현재 편성: {team.map(g=>g.name).join(' · ')||'없음'}</p><button style={btn(true)} onClick={start}><Sword size={16}/> 전투 시작</button> <button style={btn(false)} onClick={levelUp}>계정 레벨업 {save.level*300}G</button></Panel>}
 {screen==='generals'&&<Panel title="장수 관리"><div style={grid}>{generals.filter(g=>save.owned.includes(g.id)).map(g=>{const e=eq(g),s=stats(g),st=star(g),fr=save.fragments[g.id]||0;return <button key={g.id} onClick={()=>setSelected(g.id)} style={{...card,outline:selected===g.id?'2px solid #79aaff':'none'}}><b>{g.name}</b> · {g.role}<div>{'★'.repeat(st)}{'☆'.repeat(6-st)}</div><div>HP {s.hp} / ATK {s.atk}</div><div>{g.equipment} +{e.level} · {rarityName(e.rarity)}</div><small>조각 {fr}/{fragmentNeed(st)}</small></button>})}</div><GeneralPanel g={sg} st={star(sg)} fr={save.fragments[sg.id]||0} ts={save.tsSkins[sg.id]} breakthrough={breakthrough} unlockTS={unlockTS}/><EquipPanel g={sg} e={q} enhance={enhance} reroll={reroll} toggle={toggle}/></Panel>}
 {screen==='formation'&&<Panel title="장수 편성"><p>최대 5명. 위쪽 슬롯일수록 전투 배치 순서가 앞섭니다.</p><div style={grid}>{save.formation.map((id,i)=>{const g=generals.find(x=>x.id===id)!;return <div key={id} style={card}><b>{i+1}. {g.name}</b><div style={{marginTop:6}}><button style={btn(false)} onClick={()=>moveFormation(id,-1)}>▲</button> <button style={btn(false)} onClick={()=>moveFormation(id,1)}>▼</button> <button style={btn(false)} onClick={()=>toggleFormation(id)}>제외</button></div></div>})}</div><h3>보유 장수</h3><div style={grid}>{generals.filter(g=>save.owned.includes(g.id)&&!save.formation.includes(g.id)).map(g=><button key={g.id} style={card} onClick={()=>toggleFormation(g.id)}><Users size={16}/> {g.name} · ★{star(g)}</button>)}</div></Panel>}
 {screen==='inventory'&&<Panel title="전용장비 인벤토리"><div style={{display:'grid',gap:8}}>{generals.filter(g=>save.owned.includes(g.id)).map(g=>{const e=eq(g);return <div style={card} key={g.id}><b>{g.name} · {g.equipment}</b> +{e.level} {rarityName(e.rarity)} {e.equipped?'· 장착':''}<div>{e.level?`${optionNames[e.optionA]}${optionValue(e.optionA,e.level)} · ${optionNames[e.optionB]}${optionValue(e.optionB,e.level)}`:'강화하면 옵션이 활성화됩니다.'}</div></div>})}</div></Panel>}
 {screen==='summon'&&<Panel title="장수 모집"><p>1회 30 보옥 · 10회 300 보옥</p><p>10회 모집의 마지막 슬롯은 영웅 이상 등급을 보장합니다. 중복 장수는 조각 10개로 전환됩니다.</p><button style={btn(true)} onClick={()=>recruit(1)}><Gem size={16}/> 1회 모집 · 30</button> <button style={btn(true)} onClick={()=>recruit(10)}><Gem size={16}/> 10회 모집 · 300</button></Panel>}
 {screen==='battle'&&<Panel title={`천탑 ${save.floor}층 · ${turn==='player'?'아군':'적'} 턴`}><div style={board}>{Array.from({length:42},(_,i)=>{const x=i%7,y=Math.floor(i/7),t=terrain[i],u=units.find(z=>z.x===x&&z.y===y&&z.currentHp>0),can=selectedUnit?.team==='player'&&!selectedUnit.acted&&turn==='player'&&t!=='water'&&!u&&dist(selectedUnit,{x,y})<=selectedUnit.movePoints;return <button key={i} onClick={()=>u?selectCell(u):move(x,y)} style={{...cell,background:t==='forest'?'#1c3a2b':t==='hill'?'#4b3d28':t==='water'?'#18365b':t==='fort'?'#513d27':'#202938',border:target===u?.id?'2px solid #ffcc66':can?'2px solid #75aaff':'1px solid #394354'}}>{u&&<><b style={{color:u.team==='player'?'#8fc1ff':'#ff9292'}}>{u.name}</b><div>HP {u.currentHp}/{u.maxHp}</div><small>R{u.rage} {u.status!=='none'?'·'+u.status:''}</small></>}</button>})}</div><div style={actions}><button style={btn(true)} onClick={attack}>공격</button><button style={btn(false)} onClick={skill}>스킬</button><button style={btn(false)} onClick={ultimate}>궁극기</button><button style={btn(false)} onClick={endTurn}><RotateCcw size={16}/> 턴 종료</button></div><div style={card}><b>{selectedUnit?.name||'장수 선택'}</b> · MP {selectedUnit?.movePoints??'-'} · Rage {selectedUnit?.rage??'-'}{target&&<div>🎯 대상: {units.find(u=>u.id===target)?.name}</div>}{log.map((x,i)=><div key={i} style={{fontSize:13}}>{x}</div>)}</div></Panel>}
 </div>;
}
const app:CSSProperties={maxWidth:1050,margin:'0 auto',padding:16,fontFamily:'system-ui',color:'#e8edf7',background:'#101522',minHeight:'100vh'};const header:CSSProperties={display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',padding:'12px 8px',borderBottom:'1px solid #30394b'};const nav:CSSProperties={display:'flex',gap:6,flexWrap:'wrap',margin:'12px 0'};const grid:CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:8};const board:CSSProperties={display:'grid',gridTemplateColumns:'repeat(7,1fr)',gap:4,maxWidth:700};const actions:CSSProperties={display:'flex',gap:6,flexWrap:'wrap',margin:'10px 0'};const cell:CSSProperties={height:70,padding:3,color:'#fff',cursor:'pointer'};const card:CSSProperties={padding:12,border:'1px solid #343e50',borderRadius:10,background:'#171e2c',textAlign:'left'};const btn=(a:boolean):CSSProperties=>({display:'inline-flex',alignItems:'center',gap:5,padding:'9px 12px',borderRadius:8,border:'1px solid #46536a',background:a?'#294d82':'#1a2231',color:'#fff',cursor:'pointer'});
function Panel({title,children}:{title:string;children:ReactNode}){return <section style={{background:'#131a27',border:'1px solid #30394b',borderRadius:12,padding:16}}><h2 style={{marginTop:0}}>{title}</h2>{children}</section>}
function GeneralPanel({g,st,fr,ts,breakthrough,unlockTS}:{g:General;st:number;fr:number;ts:boolean;breakthrough:()=>void;unlockTS:()=>void}){return <div style={{...card,marginTop:12}}><h3 style={{marginTop:0}}><Star size={17}/> {g.name} · {g.title}</h3><div style={{fontSize:18}}>{'★'.repeat(st)}{'☆'.repeat(6-st)}</div><div>다음 돌파: 조각 {fr}/{fragmentNeed(st)} · ★1당 기본 HP/ATK +5%</div><button style={btn(true)} onClick={breakthrough}>돌파 ★{Math.min(6,st+1)}</button><h3>TS 스킨 · {g.tsName}</h3><div>{g.tsTitle} · 장식/의상 중심의 외형 변경 · 전투 능력치 변화 없음</div><div>상태: {ts?'보유':'미보유'}</div>{!ts&&<button style={btn(false)} onClick={unlockTS}><Gem size={16}/> 100 보옥으로 해금</button>}</div>}
function EquipPanel({g,e,enhance,reroll,toggle}:{g:General;e:EquipmentState;enhance:()=>void;reroll:()=>void;toggle:()=>void}){return <div style={{...card,marginTop:12}}><h3 style={{marginTop:0}}><Package size={17}/> {g.equipment} · +{e.level} {rarityName(e.rarity)}</h3><div>상태: {e.equipped?'장착':'미장착'}</div><div style={{margin:'8px 0'}}>옵션 ① {e.level?`${optionNames[e.optionA]}${optionValue(e.optionA,e.level)}`:'미활성'} · 옵션 ② {e.level?`${optionNames[e.optionB]}${optionValue(e.optionB,e.level)}`:'미활성'}</div><button style={btn(true)} onClick={enhance}><Hammer size={16}/> 강화 ({(e.level+1)*5})</button> <button style={btn(false)} onClick={reroll}>옵션 재설정 (20)</button> <button style={btn(false)} onClick={toggle}><Shield size={16}/> {e.equipped?'해제':'장착'}</button></div>}
