import { useEffect, useMemo, useState } from 'react';
import type { Terrain, Unit } from './game/types';
import { GENERAL_BY_ID } from './game/data/generals';
import { getGeneralImagePaths } from './game/data/generalImages';
import { createBattleField, createBattleFieldSeed } from './game/data/battleField';
import { createMonsterEnemies } from './game/systems/monsterBattle';
import { canEndPlayerTurn, createBattleState, endPlayerTurn, resolveEnemyTurnPhase, getSelectedReachableCells, moveBattleUnit, selectBattleTarget, selectBattleUnit, attackBattleTarget, useBattleSkill, waitBattleUnit, type BattleState } from './game/systems/battleState';
import { buildBattlePresentation } from './game/systems/battlePresentation';
import { getEnemyMovementMap, getEnemyIntentMap } from './game/systems/battleView';
import { getTowerFloorRule, getNextTowerFloor, getTowerClearReward, TOWER_MAX_FLOOR } from './game/systems/towerRules';
import { BOARD_HEIGHT, BOARD_WIDTH } from './game/data/constants';
import { applyBattleModifiers } from './game/systems/battleModifiers';
import { calculateDamage } from './game/systems/battleRules';
import { applyBattleDamageReduction } from './game/systems/battleModifiers';
import { getGeneralSkillAvailability, getSkillDescription } from './game/systems/skillRules';
import { getGeneralEffectiveStats } from './game/systems/generalStats';
import { getBattleModifiers } from './game/systems/battleModifiers';

const KEY='infinite-three-kingdoms-save-v2';
const terrainLabel:Record<Terrain,string>={plain:'평지',forest:'숲',hill:'고지',water:'물',fort:'요새'};
const statusLabel:Record<Unit['status'],string>={none:'정상',stun:'기절',burn:'화상',slow:'감속',guard:'방어'};
const statusBadge:Record<Exclude<Unit['status'],'none'>,string>={stun:'💫',burn:'🔥',slow:'🐌',guard:'🛡'};

type EquipmentState={level?:number;equipped?:boolean;optionA?:number;optionB?:number};
type SaveLike={floor?:number;level?:number;generalLevels?:Record<string,number>;formation?:string[];equipment?:Record<string,EquipmentState>;stars?:Record<string,number>;gold?:number;gems?:number;materials?:number};
function readSave():SaveLike{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
function buildPlayers(save:SaveLike):Unit[]{
 const formation=(save.formation||[]).map(id=>GENERAL_BY_ID[id]).filter(Boolean).slice(0,5);
 return formation.map((g,i)=>{
  const star=Math.max(1,Math.min(6,save.stars?.[g.id]||1)),level=Math.max(1,save.generalLevels?.[g.id]||save.level||1),eq=save.equipment?.[g.id];
  const stats=getGeneralEffectiveStats(g,{level,star,equipment:eq});
  const base:Unit={...g,skillPower:stats.skillPower,hp:stats.hp,atk:stats.atk,defense:stats.defense,maxHp:stats.hp,currentHp:stats.hp,team:'player',x:1+(i%3),y:8-Math.floor(i/3),acted:false,rage:0,buff:0,movePoints:g.move,status:'none',statusTurns:0,critChance:stats.critChance};
  return applyBattleModifiers(base,formation);
 });
}
function terrainClass(t:Terrain){return `be-terrain-${t}`}
function isPlayerActionUnavailable(u:Unit){return u.currentHp<=0||(u.status==='stun'&&u.statusTurns>0)}
function getPlayerActionState(u:Unit){if(u.currentHp<=0)return '전투불능';if(u.status==='stun'&&u.statusTurns>0)return `기절 · ${u.statusTurns}턴`;if(u.acted)return '행동 완료';return '행동 가능'}
export default function BattleEngine(){
 const[save,setSave]=useState<SaveLike>(readSave);const[towerComplete,setTowerComplete]=useState(false);const[skillMode,setSkillMode]=useState(false);const[feedback,setFeedback]=useState('');const[enemyFeed,setEnemyFeed]=useState('');const[enemyFeedStep,setEnemyFeedStep]=useState(0);const[enemyFeedTotal,setEnemyFeedTotal]=useState(0);const[engine,setEngine]=useState<BattleState|null>(null);const[terrain,setTerrain]=useState<Terrain[]>([]);const[seed,setSeed]=useState(0);const floor=save.floor||1;const rule=getTowerFloorRule(floor);const players=useMemo(()=>buildPlayers(save),[save]);
 const formationKey=useMemo(()=>players.map(player=>`${player.id}:${player.maxHp}:${player.atk}:${player.defense}:${player.critChance||0}:${player.skillPower}`).join(','),[players]);
 const completionNotice=towerComplete?'100층 천탑 정복이 저장되었습니다.':'';
 const start=()=>{setSkillMode(false);setFeedback('');setEnemyFeed('');setEnemyFeedStep(0);setEnemyFeedTotal(0);const nextSeed=createBattleFieldSeed();const nextTerrain=createBattleField(nextSeed);const enemies=createMonsterEnemies(floor);setSeed(nextSeed);setTerrain(nextTerrain);setEngine(createBattleState([...players,...enemies],[`천탑 ${floor}층 · ${rule.kind==='boss'?'BOSS':'일반'} 전투`,`지형 시드 ${nextSeed}`]));};
 useEffect(()=>{start()},[floor,formationKey]);if(!engine){return completionNotice?<section className="be-shell"><div className="be-result"><h2>천탑 완주!</h2><p>{completionNotice}</p></div></section>:null}if(terrain.length!==BOARD_WIDTH*BOARD_HEIGHT)return null;
 const presentation=buildBattlePresentation(engine.units,terrain,engine.selectedId),selected=presentation.selected;
 const moveCostMap=new Map(getSelectedReachableCells(engine,terrain).map(cell=>[`${cell.x},${cell.y}`,cell.cost]));
 const formationModifiers=getBattleModifiers(players);
 const enemyMovement=engine.turn==='enemy'?getEnemyMovementMap(engine.units,terrain):new Map<string,string[]>();const enemyIntent=engine.turn==='enemy'?getEnemyIntentMap(engine.units):new Map<string,string>();const reachable=new Set(presentation.cells.filter(c=>c.reachable).map(c=>`${c.x},${c.y}`)),targets=new Set(presentation.cells.filter(c=>c.targetable).map(c=>`${c.x},${c.y}`)),skillTargets=new Set(presentation.cells.filter(c=>c.skillTargetable).map(c=>`${c.x},${c.y}`));
 const skillAvailability=selected?getGeneralSkillAvailability(engine.units,selected.id,terrain):null;
 const skillDescription=selected?getSkillDescription(selected):null;
 const selectedTarget=engine.targetId?engine.units.find(u=>u.id===engine.targetId&&u.team==='enemy'&&u.currentHp>0):null;
 const skillReady=Boolean(selected&&skillAvailability?.ready&&(!skillAvailability.needsTarget||(selectedTarget&&skillAvailability.targetIds.includes(selectedTarget.id))));const skillTargetsCount=skillAvailability?.targetIds.length??0;const targetDamage=selected&&selectedTarget?applyBattleDamageReduction(selectedTarget,calculateDamage(selected,selectedTarget,terrain[selectedTarget.y*BOARD_WIDTH+selectedTarget.x])):null;const skillPreview=selected&&selectedTarget&&skillAvailability?.targetIds.includes(selectedTarget.id)?(()=>{const n=selected.skill;if(n==='청룡참')return `예상 피해 ${Math.max(0,Math.floor(targetDamage??0))} · 화상 2턴`;if(n==='천뢰'){const count=engine.units.filter(u=>u.team==='enemy'&&u.currentHp>0&&Math.abs(u.x-selectedTarget.x)+Math.abs(u.y-selectedTarget.y)<=1).length;return `예상 피해 ${Math.max(0,Math.floor((targetDamage??0)))} · 주변 포함 ${count}명 · 기절 2턴`;}if(n==='매혹')return '피해 없음 · 기절 2턴';if(n==='용진'){const count=engine.units.filter(u=>u.team==='enemy'&&u.currentHp>0&&((u.x===selected.x&&u.y===selectedTarget.y&&u.x===selectedTarget.x)||(u.y===selected.y&&u.x===selectedTarget.x&&u.y===selectedTarget.y))).length;return `직선 관통 · 최대 ${count}명 타격`;}return `스킬 효과 · ${selected.skill}`;})():null;
 const apply=(next:BattleState)=>{setEngine(next);if(next.phase!=='player')setSkillMode(false);};const clickCell=(x:number,y:number)=>{if(skillMode&&!selected)return;const cell=presentation.cells.find(c=>c.x===x&&c.y===y);if(cell?.unit?.team==='player'){if(skillMode)return;const next=selectBattleUnit(engine,cell.unit.id);apply(next);const chosen=next.units.find(u=>u.id===next.selectedId);if(chosen&&next.phase==='player'&&!chosen.acted&&chosen.currentHp>0&&chosen.movePoints>0){setFeedback(`${chosen.name} 선택 · 이동 가능한 타일을 표시합니다.`);window.setTimeout(()=>setFeedback(''),1400)}return}if(cell?.unit?.team==='enemy'){if(skillMode&&cell.skillTargetable){apply(selectBattleTarget(engine,cell.unit.id));setFeedback(`${cell.unit.name} 대상 선택 · 이제 스킬 사용을 눌러주세요`);return}apply(selectBattleTarget(engine,cell.unit.id));return}const result=moveBattleUnit(engine,terrain,x,y);if(result.success){apply(result.state);setFeedback(result.message||'이동 완료 · 이동 후 공격 가능');window.setTimeout(()=>setFeedback(''),1400)}};
 const act=(fn:(s:BattleState)=>{state:BattleState;success:boolean;message?:string})=>{const r=fn(engine);if(r.success){const previousLog=engine.log.length;const added=r.state.log.slice(previousLog);apply(r.state);setSkillMode(false);if(engine.phase==='enemy'&&added.length){let i=0;const show=()=>{if(i>=added.length){setEnemyFeed('');setEnemyFeedStep(0);setEnemyFeedTotal(0);return}const step=++i;setEnemyFeedStep(step);setEnemyFeedTotal(added.length);setEnemyFeed(added[step-1]);window.setTimeout(show,700)};show()}else{setFeedback(r.message||'행동 완료');window.setTimeout(()=>setFeedback(''),1400)}}};const victory=engine.phase==='victory',defeat=engine.phase==='defeat',finalFloor=floor>=100;
 const finish=()=>{if(victory){const nextFloor=getNextTowerFloor(floor);const reward=getTowerClearReward(floor);const fresh={...save,floor:nextFloor??TOWER_MAX_FLOOR,gold:(save.gold||0)+reward.gold,gems:(save.gems||0)+reward.gems,materials:(save.materials||0)+reward.materials};localStorage.setItem(KEY,JSON.stringify(fresh));setSave(fresh);if(finalFloor){setTowerComplete(true)}else{setEngine(null)}}else start()};
 return <section className="be-shell"><header className="be-header"><div><small>INFINITE THREE KINGDOMS · MANUAL SRPG</small><h2>천탑 {floor}층 {rule.kind==='boss'?'· BOSS':''}</h2><p>10×10 전장 · 랜덤 배치 지형 · 지형 효과 없음 · 수동 전투 · {formationModifiers.label}</p></div><div><span className="be-turn-count">턴 {engine.turnNumber}</span><span className={engine.turn==='player'?'be-turn':'be-turn enemy'}>{engine.turn==='player'?'PLAYER TURN':'MONSTER TURN'}</span></div></header>
  <div className="be-layout"><div>{feedback&&<div className="be-action-feedback" role="status">{feedback}</div>}{enemyFeed&&<div className="be-enemy-feed" role="status"><b>몬스터 행동 {enemyFeedStep}/{enemyFeedTotal}</b><span>{enemyFeed}</span></div>}<div className="be-grid" aria-label="10×10 랜덤 지형 전장">{presentation.cells.map(cell=>{const key=`${cell.x},${cell.y}`,u=cell.unit;const showMove=reachable.has(key)&&!u,showAttack=targets.has(key)&&u?.team==='enemy',showSkill=skillTargets.has(key),showAttackRange=cell.attackRange,showSkillRange=cell.skillRange,enemyMoveOwners=enemyMovement.get(key)??[],showEnemyMove=enemyMoveOwners.length>0&&!showMove&&!u;return <button key={key} aria-label={`${cell.x+1},${cell.y+1} ${terrainLabel[cell.terrain]}${showMove?' 이동 가능':''}${showAttack?' 공격 가능':''}${showSkill?' 스킬 대상':''}`} className={`be-cell ${terrainClass(cell.terrain)} ${showEnemyMove?'enemy-move-range':''} ${u?.team||''} ${cell.selected?'selected':''} ${u?.id===engine.targetId?'target':''} ${showMove?'reachable':''} ${showAttackRange?'attack-range':''} ${showSkillRange?'skill-range':''} ${showAttack?'targetable':''} ${showSkill?'skill-targetable':''} ${u?.team==='enemy'&&showAttack?'enemy-attackable':''} ${u?.team==='enemy'&&!showAttack&&showAttackRange?'enemy-out-of-range':''}`} onClick={()=>clickCell(cell.x,cell.y)}><span className="be-terrain-label">{terrainLabel[cell.terrain]}</span>{showMove&&<span className="be-cell-hint move">이동 {moveCostMap.get(key)??1}</span>}{showEnemyMove&&<span className="be-cell-hint enemy-move">{enemyMoveOwners.length===1?`${enemyMoveOwners[0]} 이동`:'적 이동'}</span>}{showAttackRange&&!showMove&&!u&&<span className="be-cell-hint range attack-range-label">공격권</span>}{showSkillRange&&!showMove&&!u&&<span className="be-cell-hint range skill-range-label">스킬 범위</span>}{showAttack&&<span className="be-cell-hint attack">공격</span>}{showSkill&&<span className="be-cell-hint skill">스킬 대상</span>}{u&&<><b className="be-unit-image"><img src={getGeneralImagePaths(u).sd} alt="" onError={(e)=>{e.currentTarget.style.display='none';}}/><span>{u.name.slice(0,2)}</span></b><small>{Math.max(0,u.currentHp)}/{u.maxHp}</small>{u.team==='player'&&u.currentHp>0&&u.acted&&<span className="be-acted-badge">✓ 행동 완료</span>}{engine.turn==='enemy'&&enemyIntent.get(u.id)&&<span className="be-enemy-intent">{enemyIntent.get(u.id)}</span>}{u.status!=='none'&&<span className={`be-unit-status ${u.status}`} title={`${statusLabel[u.status]} ${u.statusTurns}턴`}>{statusBadge[u.status]}<em>{u.statusTurns}</em></span>}</>}</button>})}</div>
   <div className="be-selected-info">{selected?<><div className="be-selected-top"><div><small>선택 장수</small><h3>{selected.name}</h3><p>{selected.title} · {selected.role}</p></div><span className={`be-status-pill ${selected.status}`}>{statusLabel[selected.status]}{selected.statusTurns>0?` · ${selected.statusTurns}턴`:''}</span></div><div className="be-stat-strip"><span>HP <b>{Math.max(0,selected.currentHp)}/{selected.maxHp}</b></span><span>공격 <b>{selected.atk}</b></span><span>방어 <b>{selected.defense}</b></span><span>사거리 <b>{selected.range}</b></span><span>이동 <b>{selected.movePoints}/{selected.move}</b></span><span>치명타 <b>{selected.critChance||0}%</b></span></div>{selectedTarget&&<div className="be-target-info"><small>공격 대상</small><strong>{selectedTarget.name}</strong><span>HP {Math.max(0,selectedTarget.currentHp)}/{selectedTarget.maxHp} · 방어 {selectedTarget.defense} · 거리 {Math.abs(selected.x-selectedTarget.x)+Math.abs(selected.y-selectedTarget.y)}</span>{targetDamage!==null&&<em>예상 일반공격 피해 {targetDamage}</em>}{skillPreview&&<em>✦ {skillPreview}</em>}</div>}<div className="be-synergy-line"><b>시너지</b><span>{formationModifiers.label}</span></div><div className="be-skill-line"><b>✦ {selected.skill}</b><span>위력 {selected.skillPower||'지원형'}</span><span>장비 보정 포함</span>{skillDescription&&<span className="be-skill-tooltip-wrap"><button className="be-skill-tooltip-trigger" type="button" aria-label="고유 스킬 상세 보기">?</button><span className="be-skill-tooltip" role="tooltip"><strong>{skillDescription.name}</strong><span>{skillDescription.summary}</span><span>{skillDescription.detail}</span><span>{skillDescription.targeting}</span><em>{skillDescription.powerText}</em></span></span>}</div></>:<span>장수를 선택하면 전투 스탯과 고유 스킬이 표시됩니다.</span>}</div>
   <div className="be-overlay-legend"><span className="enemy-legend">■ 적 이동 범위</span><span>적 턴에만 표시</span></div>{engine.turn==='player'&&selected&&<div className="be-range-legend" aria-label="선택 장수 범위 안내"><b className="be-range-move">이동</b><b className="be-range-attack">공격</b><b className="be-range-skill">스킬</b><span>선택 장수 기준</span></div>}<div className="be-turn-progress">{engine.phase==='player' ? (()=>{const ps=engine.units.filter(u=>u.team==='player'&&u.currentHp>0);const unavailable=ps.filter(isPlayerActionUnavailable).length;const done=ps.filter(u=>u.acted||isPlayerActionUnavailable(u)).length;return <><span>아군 행동</span><b>{done}/{ps.length}</b><i>{unavailable>0 ? ('행동 불가 '+unavailable+'명 · ') : ''}{done===ps.length?'턴 종료 가능':'행동 진행 중'}</i></>})() : <><span>몬스터 행동</span><b>적 턴</b><i>이동 범위와 행동 의도를 확인한 뒤 실행</i></>}</div><div className="be-actions"><strong>{selected?`${selected.name} · ${getPlayerActionState(selected)}`:'장수를 선택하세요'}</strong>{engine.phase==='player'&&selected&&<span className="be-action-tip">{selected.acted?'행동 완료 · 다른 장수를 선택하세요':selected.movePoints>0?`이동력 ${selected.movePoints}/${selected.move} · 이동 후 공격 또는 스킬을 사용할 수 있습니다`:'이동력 소진 · 공격 또는 스킬을 선택하세요'}</span>}<button onClick={()=>act(s=>attackBattleTarget(s,terrain))} disabled={!engine.targetId||!targets.has(`${engine.units.find(u=>u.id===engine.targetId)?.x},${engine.units.find(u=>u.id===engine.targetId)?.y}`)}>⚔ 일반공격</button><button onClick={()=>{if(skillMode&&skillReady){act(s=>useBattleSkill(s,terrain));setSkillMode(false);return}if(skillAvailability?.needsTarget){setSkillMode(true);setFeedback('스킬 사용 모드 · 보라색으로 강조된 적을 선택하세요');}else act(s=>useBattleSkill(s,terrain));}} disabled={!skillAvailability?.ready||Boolean(skillMode&&!skillReady)} title={skillAvailability?.message||'장수를 선택하세요.'}>✦ {skillMode?'대상 선택 중 · 스킬 사용':'고유 스킬'}{selected&&skillAvailability?.ready&&skillAvailability.needsTarget&&selectedTarget?` · ${selectedTarget.name}`:''}</button>{skillMode&&<button className="be-skill-cancel" onClick={()=>{setSkillMode(false);setFeedback('스킬 선택을 취소했습니다.')}}>취소</button>}<button onClick={()=>act(waitBattleUnit)} disabled={!selected||isPlayerActionUnavailable(selected)||selected.acted}>대기</button>{engine.phase==='player'&&<button onClick={()=>act(s=>endPlayerTurn(s,terrain,floor))} disabled={!canEndPlayerTurn(engine)}>몬스터 턴 시작</button>}{engine.phase==='enemy'&&<button onClick={()=>act(s=>resolveEnemyTurnPhase(s,terrain,floor))}>몬스터 행동 실행</button>}</div>
   {(victory||defeat)&&<div className="be-result"><h2>{victory?(finalFloor?'천탑 완주!':'전투 승리!'):'전투 패배...'}</h2><p>최종 턴 {engine.turnNumber} · {victory?'아군이 전장을 제압했습니다.':'아군 전원이 전투불능입니다.'}</p>{victory&&<div className="be-result-reward"><strong>{finalFloor?'100층 정복 보상':'층 클리어 보상'}</strong><span>금화 +{rule.reward.gold}</span><span>보옥 +{rule.reward.gems}</span><span>재료 +{rule.reward.materials}</span></div>}{defeat&&<p>보상은 지급되지 않습니다. 같은 층에서 다시 도전할 수 있습니다.</p>}<button onClick={finish} disabled={towerComplete}>{victory?(finalFloor?(towerComplete?'완주 완료':'완주 확인'):'다음 층'):'다시 도전'}</button></div>}</div><aside className="be-side"><h3>전투 로그</h3><p>지형 시드: {seed}</p><div className="be-log-list">{engine.log.slice(-10).reverse().map((x,i)=>{const marker=x==="몬스터 턴"||x.startsWith("전투 승리")||x.startsWith("전투 패배");return <p key={`${x}-${i}`} className={marker?"be-log-marker":""}>{marker&&<b>{x==="몬스터 턴"?"MONSTER TURN":"BATTLE RESULT"}</b>}{x}</p>})}</div><div className="be-roster"><h3>편성</h3>{presentation.playerUnits.map(u=><button key={u.id} className={`${u.id===engine.selectedId?'active ':''}${u.currentHp<=0?'defeated ':''}${u.status==='stun'&&u.statusTurns>0?'stunned':''}`} disabled={u.currentHp<=0} onClick={()=>apply(selectBattleUnit(engine,u.id))}><b>{u.name}</b><span>{getPlayerActionState(u)==='전투불능'?'전투불능':getPlayerActionState(u)==='행동 완료'?'행동 완료':getPlayerActionState(u).startsWith('기절')?getPlayerActionState(u):`HP ${Math.max(0,u.currentHp)} · 방어 ${u.defense}`}</span></button>)}</div></aside></div></section>;
}
